# Generated by Django 4.2.3 on 2023-07-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-first_name',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Список пользователей'},
        ),
    ]
