# Generated by Django 4.2.3 on 2023-07-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_productinfo_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='model',
        ),
    ]
