# Generated by Django 4.2.3 on 2023-07-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_order_price_remove_order_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='model',
        ),
    ]
